<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByKeyword($keyword)
    {
        $qb = $this->createQueryBuilder('u');

        $qb->where($qb->expr()->like('u.username',':keyword'));
        $qb->orWhere($qb->expr()->like('u.name',':keyword'));
        $qb->orWhere($qb->expr()->like('u.firstname',':keyword'));

        $qb->setParameter(':keyword','%'.$keyword.'%');

        return $qb->getQuery()->getResult();
    }
}
