# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.registration:
        class: UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.geocodingfunctions:
        class: AppBundle\Services\GeocodingFunctions
        arguments: ['%google_api_key%']

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
